export const ACTIONS = Object.freeze({
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  USER_INPUT_CHANGE: 'USER_INPUT_CHANGE',
  USER_INPUT_SUBMIT: 'USER_INPUT_SUBMIT',

  LOGOUT_PENDING: 'LOGOUT_PENDING',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
})

export const Test = {}
